### ISSUE TITLE
Request for further functionality : PG support

### ISSUE THREAD

**Issue by aimdev** [jbelien/MapFile-Generator#4]
Provide Support for postgis/postgresql.

**Comment by jbelien** [comment]
I just had a (quick) look at the code and the library and application should be able to handler PostgreSQL and PostGIS connection with `CONNECTIONTYPE`, `CONNECTION`, and `DATA` (cf. https://www.mapserver.org/input/vector/postgis.html).

Is it not the case ?
What is missing ?

**Comment by aimdev** [comment]
Hi

These are the steps taken to install, on debian9 Stretch

apt install composer

logged in as non root
composer require jbelien/mapfile-generator
                                                                                                                                                             
[InvalidArgumentException]                                                                                                                                 
Could not find package jbelien/mapfile-generator at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  

Decided to use Git

git clone https://github.com/jbelien/MapFile-Generator.git
git clone https://github.com/jbelien/MapFile-PHP-Library.git

set up apache
installed support for php7
Tested php via web browser, ok

modified settings.ini

mapserv   = "/usr/bin/mapserv"
fontset   = "/usr/lib/cgi-bin/fonts.txt"
symbolset = "/usr/lib/cgi-bin/symbols.txt"
font      = "dejavusans"
directory = "/var/www/gis/map"
library   = "/var/www/library/MapFile-PHP-Library"

Accessed remotely the tool via web browser , Blank Screen
Had to modify all occurrences of require($settings['library'].'/class.php'); to require($settings['library'].'/layerclass.php');

Accessed gui, created a test map, added layer but postgis option is not selectable. (not yet supported)

Is it possible an incorrect version was installed?

**Comment by jbelien** [comment]
> Had to modify all occurrences of require($settings['library'].'/class.php'); to require($settings['library'].'/layerclass.php');

Indeed, I noticed that yesterday as well.
Sorry about that !

I will upgrade (and fix) the library in the next few days.
And with a bit of luck, I'll find some time to add PG support in the MapFile Generator as well 😃

**Comment by aimdev** [comment]
Hi

Thanks for that. Look forward to trying it out.

**Comment by aimdev** [comment]
Hi
git cloned, then got this
composer create-project jbelien/mapfile-generator
                                                                         
  [InvalidArgumentException]                                               
  Could not find package jbelien/mapfile-generator with stability stable.  
                                                                         

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

modified composer.
diff composer.lock.original composer.lock
3805c3805
<     "minimum-stability": "dev",
---
>     "minimum-stability": "stable",
Then I had to install from debian sid php7.1 as debian stretch only has 7.0 at the moment
added required libraries from sid
apt-get install php7.1-mbstring
then
composer create-project jbelien/mapfile-generator

                                                                           
  [InvalidArgumentException]                                               
  Could not find package jbelien/mapfile-generator with stability stable.  
                                                                           

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

or

composer require jbelien/mapfile-generator
Using version ^2.0@beta for jbelien/mapfile-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jbelien/mapfile-generator dev-master -> satisfiable by jbelien/mapfile-generator[dev-master].
    - Can only install one of: jbelien/mapfile-generator[v2.0.0-beta, dev-master].
    - Installation request for jbelien/mapfile-generator ^2.0@beta -> satisfiable by jbelien/mapfile-generator[v2.0.0-beta].


Installation failed, reverting ./composer.json to its original content.

Looks like I have run out of ideas.
Can the generator run on php7.0?
re the final errors not really got any ideas what to do next

Thanks

Aimee

**Comment by jbelien** [comment]
I'm still working on the new version (so it's not ready yet).

Don't worry, everything will be working properly when I'll release `v2.0.0`.
I will also run it on Heroku so anyone can use it online (if you don't want to use it locally).

PHP 7.0 won't be supported though because Zend Expressive require PHP 7.1.

**Comment by aimdev** [comment]
I do apologise, saw the beta on github, thought it was ready for testing.
At least I have the php7.n sorted now.

**Comment by jbelien** [comment]
No worries, that's why I removed the `v2.0.0-beta` release I released yesterday.
I'll keep you up-to-data when it's ready ! 😄

**Comment by jbelien** [comment]
Now it should work ! 🎉 

No need to clone the repo, just run those 3 commands :

```
composer create-project jbelien/mapfile-generator -s beta

cd ./mapfile-generator
composer run serve --timeout 0
```

or use https://mapfile.herokuapp.com/

---

At the moment, it's not possible to load an existing MapFile but that's the next step.

**Comment by jbelien** [comment]
And the [`v2.0.0-beta` version](https://github.com/jbelien/MapFile-Generator/releases/tag/v2.0.0-beta) enables PostGIS support !

**Comment by aimdev** [comment]
Installed ok after the inevitable library hunt, required php-xml (to get the php-dom library).
Started server, accessed via the network to the server system, ie not local, works !!

**Comment by jbelien** [comment]
Awesome ! :)

I'll add the load of a MapFile in the next few days 🎉
