### ISSUE TITLE
Import of existing map files.

### ISSUE THREAD

**Issue by aimdev** [jbelien/MapFile-Generator#5]
Currently reading in a hand edited map file seems to fail as the END delimiters are not present.
Please can you confirm the END delimiters are essential?

eg
```
CLASS
   stuff
END # CLASS
```

**Comment by jbelien** [comment]
Do you use MapScript library or my `jbelien/mapfile-php-library` library ?

**Comment by aimdev** [comment]
Your php library is used, mapscript not used at all in the setup, all WMS via mapserv.

**Comment by jbelien** [comment]
I just made some checks !
I confirm that my library get confused if there is some `# xxx` missing after the `END`.
I'll try to fix that !

**Comment by jbelien** [comment]
I got a bit carried away ... I rewrote the whole library. 😂 

I still have to rewrite the `Writer` classes and I think I can release `v2.0.0` of the library.
The new version of the library implements ([almost](https://github.com/jbelien/MapFile-PHP-Library/issues/8)) every options available in MapFile (based on MapServer documentation).

**Comment by jbelien** [comment]
:sparkles: You can now import your MapFile : [`v2.1.0-beta`](https://github.com/jbelien/MapFile-Generator/tree/v2.1.0-beta) !

Feedback is of course welcome ! 👍

**Comment by aimdev** [comment]
Software loaded ok

Loading existing map got quite a lot of  Unsorted/Deprecated error, not surprised.
Seem UMN have removed the INCLUDE parameter, how annoying!!
Mine are all included types.
Looks like a bit of external editing prior to load will be needed, but once its done, shouldn't need repeating.
Is it possible to inhibit next/previous page on the browser via PHP, as using these tends to loose entries.


Made a small test map without includes, one file layer, one Postgres.
Loaded OK
Able to edit/add etc

**Comment by jbelien** [comment]
Thank you for your feedback !

> Seem UMN have removed the INCLUDE parameter, how annoying!!
> Mine are all included types.

`INCLUDE` is still supported : https://mapserver.org/mapfile/include.html
I'll add it ASAP in the library.

>  Is it possible to inhibit next/previous page on the browser via PHP, as using these tends to loose entries.

I don't get what you mean by this ?!

**Comment by aimdev** [comment]
Hi

Using the browsers previous/next page seem to make entries disappear, is what I meant to say, sorry if I confused.

On my big file load I am getting more rejects, still working through it.

However some deprecations appear to actually be supported. for example

LAYER PROCESSING fails, Mapfile document states its supported
CLASS EXPRESSION fails, Mapfile document states its supported

Or have I missed something?

Just to confirm this is only on the load, I see for example EXPRESSION is included on the page.

**Comment by jbelien** [comment]
> Using the browsers previous/next page seem to make entries disappear, is what I meant to say, sorry if I confused. 

Okay, got it, I'll have a look !

> LAYER PROCESSING fails, Mapfile document states its supported 
> CLASS EXPRESSION fails, Mapfile document states its supported 

Could you copy-paste here the content of your MapFile for those 2 issues ?
There could be something wrong with my parsing regular expression !

Thanks a lot !

**Comment by aimdev** [comment]
Hi

Here you go, this is the map and one layer, you will see I have marked the statements deprecated so I can continue down the rather large map file, which 
is over 10000 lines (thats why I broke it up into bits layer files, it gets very difficult to edit, and easily to get lost!!)


  MAP
    NAME "PLANET"
    ### Deprecated CONFIG 'ON_MISSING_DATA' 'IGNORE'
    ### Deprecated CONFIG "MS_ERRORFILE" "../debugFile.log"
    ##CONFIG "MS_ERRORFILE" "../mserror"
    ### Deprecated CONFIG 'PROJ_LIB' '../'
    FONTSET '../fonts.lst'
    IMAGETYPE png
    MAXSIZE 4000
    SIZE 800 800
    UNITS meters
    ##EXTENT -20405648.939901 -17712669.979681 20314497.045109 19408951.476421
    EXTENT -20000000 -20000000 20000000 20000000
    ### Deprecated IMAGECOLOR '#C6E2F2'
    ##SHAPEPATH '../pdata/natural_earth/'
    SHAPEPATH '../pdata/osm-data/'
    WEB
        METADATA
            "ows_enable_request" "*"
            "wms_enable_request" "*"
            "wms_srs" "EPSG:900913 EPSG:4326 EPSG:3857"
            "labelcache_map_edge_buffer" "-10"
            "wms_title" "Natural Earth World WMS"
        END
        IMAGEPATH '/tmp/ms_tmp/'
        IMAGEURL '/ms_tmp/'
    END
    DEBUG 5
    PROJECTION
        "init=epsg:3857"
    END
  	OUTPUTFORMAT
  		NAME "png_bw"
  		DRIVER AGG/PNG8
  		MIMETYPE "image/png;mode=8bit,grayscale"
  		IMAGEMODE RGB
  		EXTENSION "png"
  		### Deprecated TRANSPARENT FALSE
  		### Deprecated FORMATOPTION "PALETTE=grey.txt"
  		### Deprecated FORMATOPTION "PALETTE_FORCE=on"
	END

    ### Deprecated INCLUDE '../symbols.map'

   LAYER
   GROUP "admin"
   STATUS ON
   MAXSCALEDENOM 162504
   MINSCALEDENOM 81252
   TYPE LINE
   CONNECTIONTYPE postgis
   CONNECTION "host=localhost dbname=osm user=osm password=osm port=5432"
   NAME "borders12"
   PROJECTION
       "init=epsg:3857"
   END
   DATA "geometry from (select  geometry,osm_id,type, name as name from osm_admin where admin_level > 5) as foo using unique osm_id using srid=3857"
   LABELITEM "name"
   ## Deprecated PROCESSING "LABEL_NO_CLIP=ON"
   ## Deprecated PROCESSING "CLOSE_CONNECTION=DEFER"
   CLASSITEM "type"
   CLASS
       ## Deprecated  EXPRESSION {administrative}
       STYLE
           WIDTH 0.5
           COLOR 255 36 0
       END
       LABEL
   FONT scb
   TYPE TRUETYPE
   ENCODING "utf-8"
   SIZE 8
   COLOR 100 100 100
   OUTLINECOLOR -1 -1 -1
   OUTLINEWIDTH 2
   WRAP ' '
   MAXLENGTH 8
   ALIGN CENTER
   BUFFER 4
   PARTIALS FALSE
   POSITION cc
  END
   END
END

END

**Comment by jbelien** [comment]
I'm working on the missing parameters (see https://github.com/jbelien/MapFile-PHP-Library/issues/8).

It will "fix" most of your issues (MAP.CONFIG, LAYER.PROCESSING).

---

I checked your issue with `## Deprecated EXPRESSION {administrative}`. I didn't know that an expression could be between curly brackets but I just had a look at [the documentation](https://mapserver.org/mapfile/expressions.html) and it's indeed valid.

    CLASS
      EXPRESSION {motorway,trunk}
      #equivalent to regex EXPRESSION /motorway|trunk/
      #equivalent to mapserver EXPRESSION ("[roadtype]" IN "motorway,trunk")
      ...
    END

I'll fix it right now too 👍

**Comment by aimdev** [comment]
Hi

AFAIK the expression is added to a Postgresql sentence as an additional predicate, otherwise
the query time gets to be rather long.

The structure of the schema is quite complex, and there are two schema’s, OpenStreetMap and the one produced by Imposm3
both derived from a common file (the monde file is > 30Gb)
Suffice to say even with a powerful system and ssd’s , loads take a while.

Both your examples are valid I think, but this map was cloned from an example a while back, pre V7
so that’s probably the reason.

**Comment by jbelien** [comment]
There you go, the [MapFile PHP](https://github.com/jbelien/MapFile-PHP-Library) Library is updated :

- Add support for EXPRESSION using curly brackets
- Add support for CONFIG, DATAPATTERN, TEMPLATEPATTERN, and INCLUDE in MAP
- Add support for GEOMTRANSFORM, and PROCESSING in LAYER
- Add support for FORMATOPTION in OUTPUTFORMAT
- Add support for GEOMTRANSFORM in STYLE
