### ISSUE TITLE
Missing EXPRESSION directive

### ISSUE THREAD

**Issue by aimdev** [jbelien/MapFile-Generator#8]
Hi

LAYERS - CLASS

EXPRESSION is not visible in the Editor, despite there being a field assigned.
The EXPRESSION value exists in the LAYER segment of the MAP file (composite version)

AimDev

**Comment by jbelien** [comment]
I'm a bit confused here.

The `CLASS` : `EXPRESSION` is available in the editor :

![capture d ecran - 2018-09-23 a 15 09 59](https://user-images.githubusercontent.com/1150563/45928384-e83f2800-bf42-11e8-8a42-57e73c3fb297.png)

And according to [documentation](https://mapserver.org/mapfile/layer.html), there is no `LAYER` : `EXPRESSION`.

**Comment by aimdev** [comment]
Hi

Sorry, me getting mixed up, for some reason the expression in the map file didn't show up.
I tried another layer, works ok. 
The map file I a working from is very old so I think there are some errors not caught ( and not worth the time fixing).

Please close the issue.


AimDev
